# Generated by Django 4.1.3 on 2023-03-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eGrow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ahretamoreloco',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
